#
# Copyright (c) 2025 Conny Marco Menebröcker
#
# SPDX-License-Identifier: Apache-2.0
#

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: meinfork
      url-base: https://github.com/cmm1981
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: meinfork
      revision: stm32l100
      path: zephyr
      import: true
  self:
    path: app